// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgaQHS6hfj3Fw15hNSo2rBq352zsp0eA',
    appId: '1:85793852491:web:f39217f8b09ff9211651ce',
    messagingSenderId: '85793852491',
    projectId: 'patakazi-a667b',
    authDomain: 'patakazi-a667b.firebaseapp.com',
    storageBucket: 'patakazi-a667b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroyGbjtwv-KOLWMrHZ2Hraln_RvMEuM8',
    appId: '1:85793852491:android:9f42ede515e5ccd31651ce',
    messagingSenderId: '85793852491',
    projectId: 'patakazi-a667b',
    storageBucket: 'patakazi-a667b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9b42yPsHdkDMUunNVKSZETkigoGhoH_I',
    appId: '1:85793852491:ios:436808a67f6995cf1651ce',
    messagingSenderId: '85793852491',
    projectId: 'patakazi-a667b',
    storageBucket: 'patakazi-a667b.appspot.com',
    androidClientId: '85793852491-4id8aruvpjsvrfrs4brp8mb5a2blpek2.apps.googleusercontent.com',
    iosClientId: '85793852491-a9ln8qsp5fbail150khnv31m2lf54kk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.patakazi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9b42yPsHdkDMUunNVKSZETkigoGhoH_I',
    appId: '1:85793852491:ios:436808a67f6995cf1651ce',
    messagingSenderId: '85793852491',
    projectId: 'patakazi-a667b',
    storageBucket: 'patakazi-a667b.appspot.com',
    androidClientId: '85793852491-4id8aruvpjsvrfrs4brp8mb5a2blpek2.apps.googleusercontent.com',
    iosClientId: '85793852491-a9ln8qsp5fbail150khnv31m2lf54kk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.patakazi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBgaQHS6hfj3Fw15hNSo2rBq352zsp0eA',
    appId: '1:85793852491:web:0e02fecaccc909b21651ce',
    messagingSenderId: '85793852491',
    projectId: 'patakazi-a667b',
    authDomain: 'patakazi-a667b.firebaseapp.com',
    storageBucket: 'patakazi-a667b.appspot.com',
  );

}